version: "3.8"
services:
  webapp:
    build: ./yesterdle_minum
    command: ["codes.carroll.Main"]
    ports:
      - 8080:8080
    tty: true
    volumes:
      - type: bind
        source: mnt/
        target: /opt/project/out
  scrape:
    build: ./yesterdle_minum
    command: ["codes.carroll.scrape.Main"]
    tty: true
    volumes:
      - type: bind
        source: mnt/
        target: /opt/project/out
volumes:
  default: