schedule: "30 0 * * *"
server:
  image: criyl/yesterdle:1.0.0
  replicas: 1
  persistence:
    existingClaim: ""
    volumeName: ""
    storageClass: ""
    size: 10Gi
  service:
    type: ClusterIP
    port: 80
    nodePort: ""
    clusterIP: ""
    loadBalancerIP: ""
  resources: {}
