apiVersion: batch/v1
kind: CronJob
metadata:
  name: yesterdle-scraper-cronjob
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 150
      template:
        spec: 
          restartPolicy: Never
          volumes:
          - name: server-data
            persistentVolumeClaim:
            {{- if .Values.server.persistence.existingClaim }}
              claimName: {{ tpl .Values.server.persistence.existingClaim . }}
            {{- else }}
              claimName: pvc-yesterdle
            {{- end }}
          containers:
          - name: yesterdle-scraper
            image: {{ .Values.server.image }}
            args:
              - codes.carroll.scrape.Main
            volumeMounts:
              - mountPath: "/opt/project/out"
                name: server-data
            {{- if .Values.server.resources}}
            resources: {{ toYaml .Values.server.resources | nindent 14 }}
            {{- end }}
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
            startupProbe:
              httpGet:
                path: /status
                port: 4444
              failureThreshold: 30
              periodSeconds: 10