apiVersion: v1
kind: Service
metadata:
  labels:
    app: yesterdle-server
  name: yesterdle-service
spec:
  ports:
  - name: yesterdle-server
    port: {{ .Values.server.service.port }}
    protocol: TCP
    targetPort: 8080
  {{- if .Values.server.service.nodePort}}
  nodePort: {{ .Values.server.service.nodePort }}
  {{- end }}
  clusterIP: {{ .Values.server.service.clusterIP }}
  loadBalancerIP: {{ .Values.server.service.loadBalancerIP }}
  selector:
    app: yesterdle-server
  type: {{ .Values.server.service.type }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: yesterdle-server
  name: yesterdle-server
spec:
  serviceName: "yesterdle-service"
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: yesterdle-server
  template:
    metadata:
      labels:
        app: yesterdle-server
    spec:
      containers:
        - image: {{ .Values.server.image }}
          name: yesterdle-server
          volumeMounts:
            - mountPath: "/opt/project/out"
              name: server-data
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8080
          {{- if .Values.server.resources}}
          resources: {{ toYaml .Values.server.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: server-data
          persistentVolumeClaim:
          {{- if .Values.server.persistence.existingClaim }}
            claimName: {{ tpl .Values.server.persistence.existingClaim . }}
          {{- else }}
            claimName: pvc-yesterdle
          {{- end }}