name: Semantic Release
on:
  push:
    branches:
      - master
jobs:
  build-upload-release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        java-version: 21
        maven-version: 3.9.6
    - name: Setup Node.js and semantic-release plugins
      uses: actions/setup-node@v1
      with:
        node-version: 22
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 
    - name: Install Task
      uses: arduino/setup-task@v2
    - name: 'Setup yq'
      uses: dcarbone/install-yq-action@v1.1.1
      with:
        version: 'v4.9.6'
        download-compressed: 'true'
        force: 'false'
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator
          @semantic-release/exec
          @semantic-release/git
          @semantic-release/github
          @semantic-release/commit-analyzer
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}